[[LogDensityProblems]]
repo-rev = "master"
repo-url = "https://github.com/tpapp/LogDensityProblems.jl"
uuid = "025064c8-8453-11e8-27bf-e54b7298189f"
version = "0.1.0"

[[TransformVariables]]
repo-rev = "master"
repo-url = "https://github.com/tpapp/TransformVariables.jl"
uuid = "eb4f743c-8036-11e8-1c4c-19fb1cbfc623"
version = "0.1.0"
